/**
 * JASPER Blog Posts API
 * Handles CRUD operations for blog posts
 * Supports scheduling, draft status, and AI auto-posting
 *
 * SEED DATA: 10 AI-generated DFI articles for live site
 */
import { jwtVerify } from 'jose';

const SECRET_KEY = process.env.SECRET_KEY || 'jasper-default-secret-key-change-in-production';
const AI_API_KEY = process.env.BLOG_AI_API_KEY || 'jasper-ai-blog-key';

function getSecretKey() {
  return new TextEncoder().encode(SECRET_KEY);
}

async function verifyAuth(req) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return null;
  }
  const token = authHeader.substring(7);
  try {
    const { payload } = await jwtVerify(token, getSecretKey());
    return payload;
  } catch (error) {
    return null;
  }
}

function verifyAIKey(req) {
  const apiKey = req.headers['x-ai-api-key'];
  return apiKey === AI_API_KEY;
}

const POST_STATUSES = ['draft', 'scheduled', 'published'];

const CATEGORIES = [
  'DFI Insights',
  'Financial Modelling',
  'Sector Analysis',
  'Case Studies',
  'Industry News',
  'Climate Finance'
];

// ============================================================================
// SEED DATA: 10 AI-Generated Articles for Live Site
// Generated by JASPER Content System using Gemini 3.0 Flash + DeepSeek V3.2
// ============================================================================

let blogPosts = [
  // Article 1: IDC Funding Guide (Featured)
  {
    id: 'post-jasper-001',
    slug: 'idc-funding-requirements-south-africa-2025',
    title: 'IDC Funding Requirements: The Complete 2025 Guide for South African Businesses',
    excerpt: 'Navigate the Industrial Development Corporation funding landscape with confidence. This comprehensive guide covers eligibility criteria, application process, sector priorities, and how to structure your financial model for IDC approval.',
    content: `## Understanding the IDC's Mission

The Industrial Development Corporation (IDC) is South Africa's premier development finance institution, with over R130 billion in assets under management. For 2025, the IDC has committed R50 billion to support industrialisation, job creation, and economic transformation.

## Eligibility Criteria

### 1. Sector Alignment

The IDC prioritises funding for businesses operating in:

- **Manufacturing & Agro-processing** - Value-added production with export potential
- **Mining & Mineral Beneficiation** - Downstream processing and green mining
- **Infrastructure & Logistics** - Transport, warehousing, and port facilities
- **Green Industries** - Renewable energy, waste management, and circular economy
- **Tourism & Hospitality** - Sustainable tourism and local content

### 2. Financial Requirements

Your business must demonstrate:

- **Minimum equity contribution**: 30-40% of total project cost
- **Debt Service Coverage Ratio (DSCR)**: Above 1.3x throughout the loan term
- **Realistic projections**: Revenue backed by offtake agreements or market research
- **Working capital adequacy**: Sufficient buffer for operational needs

### 3. Development Impact

The IDC assesses applications on development outcomes:

| Metric | Target |
|--------|--------|
| Jobs per R1 million | Minimum 5 direct jobs |
| BEE ownership | 30%+ black ownership preferred |
| Geographic focus | Rural and township economies prioritised |
| Skills development | Training programmes required |

## Application Process

### Step 1: Pre-Assessment (2-4 weeks)

Submit your business plan with:
- Executive summary and value proposition
- Market analysis and competitive landscape
- Management team profiles
- 5-year financial projections

### Step 2: Due Diligence (6-12 weeks)

The IDC will evaluate:
- Legal and compliance status
- Environmental impact assessments
- Technical feasibility studies
- BEE credentials and scorecards

### Step 3: Credit Approval (4-8 weeks)

Internal credit committees assess:
- Financial model integrity
- Security arrangements
- Condition precedents
- Disbursement schedules

## Financial Model Requirements

Your integrated financial model should include:

1. **Income Statement Projections**
   - Revenue build-up with unit economics
   - Cost structure with escalation assumptions
   - EBITDA margins by year

2. **Balance Sheet Forecasts**
   - Working capital requirements
   - Fixed asset schedules
   - Debt and equity structure

3. **Cash Flow Statements**
   - Operating cash flow
   - Investment requirements
   - Financing activities

4. **Sensitivity Analysis**
   - Revenue variance scenarios
   - Cost escalation impacts
   - Interest rate sensitivity

## Common Pitfalls to Avoid

1. **Over-optimistic projections** - Base your model on conservative assumptions with documented sources
2. **Inadequate security** - Prepare asset registers and valuations upfront
3. **Missing documentation** - Gather all certificates, agreements, and legal opinions beforehand
4. **Weak development narrative** - Quantify job creation and transformation impact

## How JASPER Supports IDC Applications

Our JASPER financial modelling platform is specifically designed for DFI applications:

- **Zero reference errors** - Every formula validated
- **IDC-compliant ratios** - DSCR, LLCR, and project returns calculated correctly
- **Scenario modelling** - Base, upside, and downside cases
- **Professional output** - Investment-grade presentation

---

*Ready to start your IDC application? [Contact our team](/contact) for a consultation on structuring your financial model.*`,
    category: 'DFI Insights',
    tags: ['IDC', 'Development Finance', 'South Africa', 'Funding Requirements', 'Financial Modelling', 'BEE'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-12-20T09:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-12-20T09:00:00Z',
    readTime: 12,
    featured: true,
    heroImage: null,
    seoTitle: 'IDC Funding Requirements 2025 | Complete Guide for SA Businesses',
    seoDescription: 'Comprehensive guide to IDC funding requirements in South Africa. Learn eligibility criteria, application process, and financial model requirements for approval.',
    seo: { score: 92, title: 'IDC Funding Requirements 2025', description: 'Complete IDC funding guide' },
    status: 'published',
    createdAt: '2024-12-20T08:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'gemini-3.0-flash-preview'
  },

  // Article 2: AfDB Project Finance
  {
    id: 'post-jasper-002',
    slug: 'afdb-project-finance-infrastructure-africa',
    title: 'African Development Bank Project Finance: Structuring Infrastructure Deals',
    excerpt: 'Learn how to structure infrastructure projects for AfDB financing. From transport to energy, discover the financial structures, risk allocation, and bankability requirements that attract DFI investment.',
    content: `## AfDB's Infrastructure Mandate

The African Development Bank Group has committed over $50 billion to infrastructure development across the continent. Their High 5 priorities include Light Up and Power Africa, Feed Africa, Industrialise Africa, Integrate Africa, and Improve the Quality of Life.

## Project Finance Fundamentals

### What is Project Finance?

Project finance is a non-recourse or limited-recourse financing structure where:

- **Repayment depends** on project cash flows, not sponsor balance sheets
- **Assets and contracts** serve as security for lenders
- **Risk is allocated** to parties best able to manage it
- **Special Purpose Vehicle (SPV)** isolates project risks

### When to Use Project Finance

| Suitable Projects | Less Suitable |
|-------------------|---------------|
| Power plants | Working capital |
| Toll roads | R&D ventures |
| Port terminals | Start-ups |
| Mining operations | Service businesses |

## AfDB Financing Products

### 1. Senior Debt

- **Tenure**: Up to 20 years for infrastructure
- **Interest rates**: SOFR/EURIBOR + margin (200-400 bps)
- **Grace periods**: Aligned with construction phase
- **Currency**: USD, EUR, or local currency where available

### 2. Subordinated Debt / Mezzanine

- **Risk absorption**: Subordinate to senior lenders
- **Higher returns**: Reflects increased risk profile
- **Flexibility**: Convertible or PIK options

### 3. Equity Investments

- **Direct equity**: AfDB takes ownership stake
- **Africa Growing Together Fund**: Co-investment vehicle
- **Exit mechanisms**: IPO, trade sale, or buyback

## Bankability Requirements

### Revenue Security

Your project must demonstrate:

- **Offtake agreements**: Creditworthy buyers with long-term contracts
- **Tariff certainty**: Regulatory frameworks supporting cost recovery
- **Volume risk mitigation**: Take-or-pay structures where possible

### Construction Risk

Address EPC arrangements:

- **Fixed-price turnkey contracts** from reputable contractors
- **Performance guarantees** and liquidated damages
- **Completion support** from sponsors if required

### Operating Risk

Plan for operational phase:

- **O&M agreements** with experienced operators
- **Major maintenance reserves** funded from operations
- **Insurance programme** covering all material risks

## Financial Model Standards

AfDB requires models that demonstrate:

1. **Debt Service Coverage Ratio (DSCR)**
   - Minimum 1.3x for infrastructure
   - 1.4x for projects with volume risk
   - 1.5x for greenfield with construction risk

2. **Loan Life Coverage Ratio (LLCR)**
   - NPV of cash flows over loan life divided by debt outstanding
   - Typically above 1.4x

3. **Project Internal Rate of Return (IRR)**
   - Base case above weighted cost of capital
   - Stress cases demonstrate resilience

## Risk Allocation Matrix

| Risk Category | Allocation |
|---------------|------------|
| Construction | EPC Contractor |
| Technology | Equipment Supplier |
| Operations | O&M Contractor |
| Revenue | Offtaker / Government |
| Currency | Sponsors / Hedging |
| Political | DFI / Insurance |

## Application Tips

1. **Early engagement** - Consult AfDB sector teams during feasibility
2. **E&S compliance** - Meet IFC Performance Standards upfront
3. **Local content** - Demonstrate African sourcing and employment
4. **Co-financing** - Identify commercial banks for syndication

---

*Planning an infrastructure project in Africa? [Contact JASPER](/contact) for bankable financial modelling.*`,
    category: 'DFI Insights',
    tags: ['AfDB', 'Project Finance', 'Infrastructure', 'Africa', 'Development Finance', 'PPP'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-12-18T10:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-12-18T10:00:00Z',
    readTime: 14,
    featured: false,
    heroImage: null,
    seoTitle: 'AfDB Project Finance | Infrastructure Funding Guide Africa',
    seoDescription: 'Structure infrastructure deals for African Development Bank financing. Learn bankability requirements, risk allocation, and financial model standards.',
    seo: { score: 88, title: 'AfDB Project Finance', description: 'Infrastructure financing guide' },
    status: 'published',
    createdAt: '2024-12-18T09:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'gemini-3.0-flash-preview'
  },

  // Article 3: Renewable Energy Finance
  {
    id: 'post-jasper-003',
    slug: 'renewable-energy-project-finance-africa-2025',
    title: 'Renewable Energy Project Finance in Africa: Solar, Wind, and Beyond',
    excerpt: 'Unlock funding for your renewable energy project. From utility-scale solar to distributed wind, learn how to structure bankable deals that attract DFI and climate finance investment.',
    content: `## The African Renewable Energy Opportunity

Africa has the world's best solar resources and significant wind potential, yet only 2% of global renewable energy investment flows to the continent. This gap represents a massive opportunity for developers who understand DFI requirements.

## Market Overview 2025

### Installed Capacity Targets

| Country | 2030 Target | Current Progress |
|---------|-------------|------------------|
| South Africa | 25 GW renewables | 8 GW operational |
| Egypt | 42% renewable | 20% achieved |
| Morocco | 52% renewable | 40% achieved |
| Kenya | 100% renewable | 90% achieved |

### Key Drivers

- **Grid deficits** - 600 million Africans lack reliable electricity
- **Cost competitiveness** - Solar LCOE below $30/MWh in optimal locations
- **Climate commitments** - NDCs require rapid decarbonisation
- **Foreign exchange** - Renewables reduce fuel import dependency

## Financing Structures

### Utility-Scale Projects

For projects above 50 MW:

- **Project finance** with 15-20 year debt tenors
- **DSCR requirements** of 1.3x for solar, 1.4x for wind
- **Currency solutions** via DFI partial guarantees
- **PPA counterparties** typically utilities or large corporates

### Commercial & Industrial (C&I)

For 1-50 MW installations:

- **Asset finance** or lease structures
- **Shorter tenors** of 7-12 years
- **Corporate PPAs** with credit enhancement
- **Aggregation platforms** for smaller projects

### Distributed Generation

For sub-MW installations:

- **Pay-as-you-go** consumer financing
- **Mini-grid concessions** in rural areas
- **Results-based financing** from DFIs

## DFI Partners for Renewables

### Multilateral DFIs

- **IFC** - Climate Business anchor investor
- **AfDB** - Desert to Power initiative
- **EIB** - GET programme for climate
- **AIIB** - Infrastructure focus

### Bilateral DFIs

- **FMO** (Netherlands) - Strong Africa portfolio
- **DEG** (Germany) - Green energy mandate
- **OPIC/DFC** (USA) - Power Africa partner
- **CDC** (UK) - Just transition focus

### Climate Funds

- **Green Climate Fund** - Concessional tranches
- **Climate Investment Funds** - CTF and SREP
- **SEFA** - AfDB's Sustainable Energy Fund

## Financial Model Requirements

### Revenue Projections

Model these elements:

1. **Resource assessment** - P50, P75, P90 scenarios for solar/wind
2. **Degradation curves** - 0.5% p.a. for solar panels
3. **Availability factors** - 97%+ for well-maintained plants
4. **Curtailment risks** - Grid dispatch priorities

### Cost Structure

Include realistic assumptions:

- **Capital costs** - $600-800k/MW for utility solar
- **O&M costs** - $8-12k/MW/year for solar
- **Major maintenance** - Inverter replacement in years 10-12
- **Insurance** - 0.3-0.5% of asset value

### Key Metrics

Lenders evaluate:

| Metric | Solar Target | Wind Target |
|--------|--------------|-------------|
| Base Case DSCR | 1.30x | 1.40x |
| P90 DSCR | 1.15x | 1.20x |
| LLCR | 1.40x | 1.50x |
| Project IRR | 12-15% | 14-18% |

## Success Factors

1. **Resource quality** - High irradiance or wind speeds
2. **Grid connection** - Proximity to substations
3. **Land security** - Clear title and permits
4. **Offtaker credit** - Utility or corporate creditworthiness
5. **Local content** - Meeting IRP requirements

---

*Developing a renewable energy project? [Contact JASPER](/contact) for DFI-ready financial models.*`,
    category: 'Sector Analysis',
    tags: ['Renewable Energy', 'Solar', 'Wind', 'Project Finance', 'Africa', 'Climate Finance', 'DFI'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-12-15T11:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-12-15T11:00:00Z',
    readTime: 13,
    featured: false,
    heroImage: null,
    seoTitle: 'Renewable Energy Project Finance Africa | Solar & Wind Funding Guide',
    seoDescription: 'Complete guide to renewable energy project finance in Africa. Learn DFI requirements, financial modelling standards, and how to structure bankable solar and wind deals.',
    seo: { score: 90, title: 'Renewable Energy Finance Africa', description: 'Solar and wind project funding' },
    status: 'published',
    createdAt: '2024-12-15T10:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'deepseek-chat'
  },

  // Article 4: Financial Model Best Practices
  {
    id: 'post-jasper-004',
    slug: 'financial-model-best-practices-dfi-funding',
    title: '10 Financial Model Best Practices for DFI Funding Applications',
    excerpt: 'Avoid costly errors and build investor-ready financial models. Learn the techniques that separate amateur spreadsheets from professional-grade analysis that DFIs expect.',
    content: `## Why Model Quality Matters

A poorly constructed financial model can derail your entire funding application. DFIs review thousands of applications annually, and models with errors, unclear assumptions, or unprofessional presentation get rejected quickly.

## Best Practice 1: Separate Inputs from Calculations

### The Three-Layer Architecture

Structure your model with:

- **Input sheets** - All assumptions in one place (highlighted in blue)
- **Calculation sheets** - Formulas only, no hardcoded values
- **Output sheets** - Formatted for presentation and printing

### Example Structure

\`\`\`
1_Assumptions        (INPUT)
2_Revenue_Build      (CALC)
3_Operating_Costs    (CALC)
4_CapEx_Schedule     (CALC)
5_Debt_Schedule      (CALC)
6_Financial_Statements (OUTPUT)
7_Returns_Analysis   (OUTPUT)
8_Sensitivity        (OUTPUT)
\`\`\`

## Best Practice 2: Eliminate All Errors

### Zero-Error Standard

DFI models must have:

- **No #REF! errors** - Check references after any structural changes
- **No #VALUE! errors** - Validate all data types
- **No circular references** - Use iterative calculations only when necessary
- **Balance sheet balances** - Assets = Liabilities + Equity always

### Error Checking Formula

Add validation rows:

\`\`\`excel
=IF(ABS(TotalAssets-TotalLiabilities-TotalEquity)<0.01,"OK","ERROR")
\`\`\`

## Best Practice 3: Document Every Assumption

### Source Citations

Every input needs:

- **Source document** or research reference
- **Date of data** to track staleness
- **Rationale** for projection methodology
- **Sensitivity range** for stress testing

### Example Documentation

| Assumption | Value | Source | Date |
|------------|-------|--------|------|
| Inflation rate | 5.5% | SARB forecast | Dec 2024 |
| Exchange rate | R18.50 | Forward curve | Dec 2024 |
| Revenue growth | 15% | Management | Q4 2024 |

## Best Practice 4: Build in Flexibility

### Scenario Toggles

Create dropdown selectors for:

- **Base / Upside / Downside** cases
- **Different product lines** or markets
- **Construction vs operations** phases
- **Currency options** for multi-currency projects

### Data Validation

Use Excel data validation for scenario inputs:

\`\`\`excel
=INDIRECT("Scenario_"&ScenarioSelector&"_Revenue")
\`\`\`

## Best Practice 5: Use Consistent Formatting

### Visual Hierarchy

Apply consistent formatting:

| Element | Font Color | Background | Style |
|---------|------------|------------|-------|
| Hardcoded inputs | Blue | Light yellow | Normal |
| Formulas | Black | None | Normal |
| Cross-sheet links | Green | None | Normal |
| Headers | Black | Grey | Bold |
| Check cells | Red/Green | None | Bold |

## Best Practice 6: Calculate Key DFI Ratios

### Required Metrics

Every DFI model needs:

1. **DSCR** - Net Operating Income / Debt Service
2. **LLCR** - NPV(Cash Flow to Debt) / Outstanding Debt
3. **Project IRR** - Before financing returns
4. **Equity IRR** - After debt service returns
5. **Payback Period** - Time to recover investment

### DSCR Formula

\`\`\`excel
=EBITDA / (Principal_Repayment + Interest_Expense)
\`\`\`

## Best Practice 7: Stress Test Thoroughly

### Key Scenarios

Model these stress cases:

- **Revenue -20%** from base case
- **Operating costs +15%** escalation
- **Construction delay** of 6 months
- **Currency depreciation** of 20%
- **Interest rate increase** of 200 bps

### Tornado Diagrams

Show sensitivity visually with waterfall charts indicating which variables have the most impact on returns.

## Best Practice 8: Include Cash Flow Waterfall

### Monthly Granularity

Show cash flows during:

- **Construction period** - Drawdowns, equity injections
- **Ramp-up period** - Gradual revenue increase
- **Operations** - Quarterly or annual thereafter

### Waterfall Components

\`\`\`
Revenue
- Operating Costs
= EBITDA
- Taxes
- Working Capital
- CapEx
= Free Cash Flow
- Debt Service
= Equity Cash Flow
\`\`\`

## Best Practice 9: Present Professionally

### Output Standards

Ensure outputs:

- **Print cleanly** on A4/Letter paper
- **Include headers** with project name and date
- **Show page numbers** for easy reference
- **Use consistent number formats** (thousands, millions)
- **Include chart visualisations** of key metrics

## Best Practice 10: Version Control

### File Naming Convention

\`\`\`
[Project]_FinModel_v[X.Y]_[YYYYMMDD].xlsx
\`\`\`

Example: FreshHarvest_FinModel_v2.3_20241220.xlsx

### Change Log

Maintain a change log sheet documenting:
- Version number and date
- Changes made
- Author
- Review status

---

*Need a professional financial model? [Contact JASPER](/contact) for DFI-compliant modelling services.*`,
    category: 'Financial Modelling',
    tags: ['Financial Modelling', 'Excel', 'Best Practices', 'DFI', 'Due Diligence', 'Investment'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-12-12T08:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-12-12T08:00:00Z',
    readTime: 11,
    featured: false,
    heroImage: null,
    seoTitle: '10 Financial Model Best Practices for DFI Funding | JASPER Guide',
    seoDescription: 'Learn 10 essential financial model best practices for DFI funding applications. From structure to error elimination, build investor-ready spreadsheets.',
    seo: { score: 85, title: 'Financial Model Best Practices', description: 'DFI modelling standards' },
    status: 'published',
    createdAt: '2024-12-12T07:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'gemini-3.0-flash-preview'
  },

  // Article 5: Agri-Processing Finance
  {
    id: 'post-jasper-005',
    slug: 'agri-processing-finance-africa-dfi-funding',
    title: 'Agri-Processing Finance in Africa: From Farm Gate to Export',
    excerpt: 'Discover how to finance agricultural processing facilities in Africa. Learn about DFI appetite for agri-industrialisation, value chain financing, and structuring bankable projects.',
    content: `## The Agri-Processing Opportunity

Africa imports over $40 billion in food annually, yet has 60% of the world's uncultivated arable land. Agri-processing bridges this gap, creating value-added products for domestic consumption and export.

## Why DFIs Love Agri-Processing

### Development Impact

Agri-processing delivers on all DFI priorities:

- **Job creation** - Labour-intensive operations in rural areas
- **Smallholder inclusion** - Contract farming and outgrower schemes
- **Food security** - Reducing import dependency
- **Export earnings** - Foreign exchange generation
- **Women's empowerment** - High female participation rates

### Sector Economics

| Subsector | Gross Margins | Job Intensity |
|-----------|--------------|---------------|
| Fruit processing | 25-35% | 15 jobs/R1M |
| Grain milling | 15-20% | 8 jobs/R1M |
| Meat processing | 12-18% | 12 jobs/R1M |
| Dairy | 18-25% | 10 jobs/R1M |
| Oilseed crushing | 10-15% | 6 jobs/R1M |

## Financing Structures

### Corporate Finance

For established agri-businesses:

- **Term loans** secured against fixed assets
- **Working capital facilities** for seasonal needs
- **Trade finance** for export shipments
- **Warehouse receipt financing** for stored commodities

### Project Finance

For greenfield processing plants:

- **SPV structure** ring-fencing project risks
- **Offtake agreements** with retailers or exporters
- **Supplier contracts** with farmer cooperatives
- **EPC arrangements** for turnkey construction

### Value Chain Finance

For integrated supply chains:

- **Input financing** for seeds, fertiliser, equipment
- **Pre-harvest finance** against crop pledges
- **Post-harvest storage** with warehouse receipts
- **Processing credit** for millers and processors

## Key DFI Partners

### Multilateral

- **IFC** - Agribusiness and food security focus
- **AfDB** - Feed Africa initiative
- **IFAD** - Smallholder integration

### Bilateral

- **DEG** - Strong agri portfolio
- **FMO** - Sustainability focus
- **CDC** - Patient capital for scale

### Specialist Funds

- **Africa Agriculture and Trade Investment Fund (AATIF)**
- **Phatisa Food Fund** - Africa-focused PE
- **AgDevCo** - Early-stage developer

## Financial Model Essentials

### Revenue Drivers

Model comprehensively:

1. **Raw material sourcing** - Volumes, prices, seasonal patterns
2. **Processing yields** - Conversion ratios by product
3. **Product mix** - Grade distribution and pricing
4. **Sales channels** - Domestic vs export, retail vs wholesale

### Cost Structure

Include all elements:

- **Raw materials** - 50-70% of revenue typically
- **Energy** - Electricity, steam, refrigeration
- **Labour** - Direct and overhead
- **Packaging** - Critical for food products
- **Logistics** - Cold chain where required

### Working Capital

Model seasonal patterns:

- **Harvest season** build-up of inventory
- **Processing cycle** times
- **Debtor days** by customer segment
- **Creditor management** with suppliers

## Risk Mitigation

### Supply Risk

- **Contract farming** with fixed pricing
- **Outgrower schemes** with technical support
- **Multiple sourcing** regions/suppliers
- **Buffer stock** management

### Market Risk

- **Offtake agreements** with anchor buyers
- **Price hedging** for commodities
- **Product diversification** across grades
- **Geographic spread** of customers

### Operational Risk

- **Quality management** systems (ISO, HACCP)
- **Experienced operators** and technical partners
- **Maintenance programmes** for equipment
- **Insurance coverage** comprehensive

## Case Example: Fruit Processing

A 10,000 TPA fruit processing facility:

| Metric | Value |
|--------|-------|
| Total Investment | R85 million |
| Debt:Equity | 60:40 |
| Loan Tenor | 8 years |
| DSCR (Min) | 1.35x |
| Project IRR | 18% |
| Jobs Created | 120 direct |
| Smallholders Linked | 500 farmers |

---

*Planning an agri-processing investment? [Contact JASPER](/contact) for sector-specific financial modelling.*`,
    category: 'Sector Analysis',
    tags: ['Agriculture', 'Agri-Processing', 'Food Security', 'Africa', 'DFI', 'Value Chain Finance'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-12-10T14:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-12-10T14:00:00Z',
    readTime: 12,
    featured: false,
    heroImage: null,
    seoTitle: 'Agri-Processing Finance Africa | DFI Funding for Agriculture',
    seoDescription: 'Finance agricultural processing in Africa. Learn about DFI appetite for agri-industrialisation, value chain financing, and bankable project structures.',
    seo: { score: 86, title: 'Agri-Processing Finance Africa', description: 'Agricultural DFI funding' },
    status: 'published',
    createdAt: '2024-12-10T13:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'deepseek-chat'
  },

  // Article 6: Green Climate Fund
  {
    id: 'post-jasper-006',
    slug: 'green-climate-fund-gcf-project-funding-guide',
    title: 'Green Climate Fund: Accessing GCF Project Funding in Africa',
    excerpt: 'Navigate the Green Climate Fund application process. Learn about GCF accreditation, project approval criteria, and how to structure climate-focused investments for concessional finance.',
    content: `## Understanding the Green Climate Fund

The Green Climate Fund (GCF) is the world's largest climate fund, with over $30 billion in pledged resources. It provides concessional finance for mitigation and adaptation projects in developing countries.

## GCF Funding Windows

### Mitigation Projects

Reducing greenhouse gas emissions through:

- **Renewable energy** deployment
- **Energy efficiency** improvements
- **Sustainable transport** solutions
- **Forest conservation** and REDD+
- **Industrial decarbonisation**

### Adaptation Projects

Building climate resilience through:

- **Water security** infrastructure
- **Climate-smart agriculture**
- **Coastal protection** measures
- **Early warning systems**
- **Health sector adaptation**

## Accessing GCF Finance

### Accredited Entities

Projects must be submitted by accredited entities:

- **International** - AfDB, IFC, UNDP, GIZ
- **Regional** - BOAD, DBSA, CDG Capital
- **National** - SANBI (South Africa), NEMA (Kenya)
- **Private Sector** - Select commercial banks

### Project Categories

| Category | Project Size | Approval Process |
|----------|-------------|------------------|
| Micro | < $10M | Simplified |
| Small | $10-50M | Standard |
| Medium | $50-250M | Standard |
| Large | > $250M | Enhanced |

## GCF Investment Criteria

### Paradigm Shift Potential

Projects must demonstrate:

- **Scale** - Potential for replication and scaling
- **Transformation** - Systemic change in sector/region
- **Sustainability** - Long-term impact beyond project life
- **Innovation** - New approaches or technologies

### Climate Impact

Quantify outcomes:

- **Tonnes of CO2 equivalent** avoided (mitigation)
- **Number of beneficiaries** reached (adaptation)
- **Cost per tonne** or per beneficiary
- **Additionality** over business-as-usual

### Financial Viability

Demonstrate bankability:

- **Co-financing ratio** (GCF typically 30-50%)
- **Financial sustainability** post-GCF support
- **Concessionality** justification
- **Exit strategy** for GCF participation

### Safeguards Compliance

Meet environmental and social standards:

- **GCF ESS** - Eight safeguard areas
- **Gender Policy** - Gender-responsive design
- **Indigenous Peoples** policy where applicable
- **Stakeholder engagement** throughout

## Financial Structuring

### Concessionality Tools

GCF provides:

- **Concessional loans** - Below-market rates
- **Grants** - For adaptation and enabling activities
- **Equity** - For high-risk/high-impact projects
- **Guarantees** - To crowd in private finance

### Blended Finance

Typical structure for private sector projects:

\`\`\`
Total Project: $100M
├── GCF Concessional Loan: $30M (5%, 15 years)
├── DFI Senior Debt: $40M (Commercial terms)
├── Sponsor Equity: $20M
└── Local Bank Debt: $10M
\`\`\`

## Application Process

### Stage 1: Concept Note

Submit initial concept covering:
- Problem statement and climate rationale
- Project description and location
- Expected climate impact
- Indicative financing structure

### Stage 2: Full Funding Proposal

Detailed documentation:
- Feasibility study and technical design
- Environmental and social impact assessment
- Gender assessment and action plan
- Financial model and implementation plan

### Stage 3: Board Approval

GCF Board review considers:
- Investment criteria assessment
- Independent TAP review
- Accredited entity recommendation
- Risk assessment

### Timeline

| Stage | Duration |
|-------|----------|
| Concept development | 3-6 months |
| Concept approval | 1-2 months |
| Funding proposal | 6-12 months |
| Board approval | 2-3 months |
| Legal execution | 3-6 months |
| **Total** | **15-29 months** |

## Success Tips

1. **Early AE engagement** - Select accredited entity based on sector expertise
2. **Strong climate rationale** - Quantify impact with credible methodology
3. **Robust safeguards** - Exceed minimum requirements
4. **Private sector leverage** - Maximise co-financing
5. **Country ownership** - Align with NDC and national priorities

---

*Pursuing GCF funding? [Contact JASPER](/contact) for climate finance structuring and financial modelling.*`,
    category: 'Climate Finance',
    tags: ['Green Climate Fund', 'GCF', 'Climate Finance', 'Concessional Finance', 'Africa', 'Adaptation', 'Mitigation'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-12-08T09:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-12-08T09:00:00Z',
    readTime: 13,
    featured: false,
    heroImage: null,
    seoTitle: 'Green Climate Fund GCF Funding | Africa Project Guide',
    seoDescription: 'Access Green Climate Fund project funding. Learn GCF accreditation, approval criteria, and how to structure climate investments for concessional finance.',
    seo: { score: 84, title: 'GCF Funding Guide', description: 'Green Climate Fund projects' },
    status: 'published',
    createdAt: '2024-12-08T08:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'gemini-3.0-flash-preview'
  },

  // Article 7: Data Centres in Africa
  {
    id: 'post-jasper-007',
    slug: 'data-centre-financing-africa-digital-infrastructure',
    title: 'Financing Data Centres in Africa: The Digital Infrastructure Opportunity',
    excerpt: 'Africa hosts less than 2% of global data centre capacity. Learn how to finance data centre investments in Africa, from site selection to power infrastructure to DFI funding structures.',
    content: `## The Digital Infrastructure Gap

Africa's data centre capacity lags far behind demand. With cloud adoption accelerating and data localisation requirements emerging, the continent needs massive investment in digital infrastructure.

## Market Fundamentals

### Capacity Gap

| Region | Data Centre Capacity | Population |
|--------|---------------------|------------|
| North America | 2,500+ MW | 370M |
| Europe | 1,800+ MW | 450M |
| Asia Pacific | 3,000+ MW | 4.5B |
| **Africa** | **<100 MW** | **1.4B** |

### Demand Drivers

- **Cloud computing** adoption by enterprises
- **Mobile data** explosion (30%+ CAGR)
- **Data sovereignty** regulations requiring local storage
- **E-commerce** growth and fintech expansion
- **Government digitisation** programmes

## Investment Considerations

### Site Selection

Critical factors:

- **Power availability** - Reliable grid or captive generation
- **Fibre connectivity** - Multiple carrier access
- **Land security** - Industrial zoning and title
- **Climate** - Cooling efficiency considerations
- **Political stability** - Long-term asset protection

### Power Infrastructure

Data centres are energy-intensive:

- **Power Usage Effectiveness (PUE)** - Target 1.4-1.6 for Africa
- **Backup generation** - N+1 diesel generators minimum
- **UPS systems** - Battery backup for seamless switchover
- **Renewable integration** - Solar/wind for cost and ESG

### Connectivity

Essential infrastructure:

- **Submarine cable** proximity (SAT-3, WACS, SEACOM)
- **Terrestrial fibre** networks for last mile
- **Carrier neutrality** - Multiple telco access
- **Internet exchange** connectivity

## Financial Model Structure

### Revenue Model

\`\`\`
Revenue = Contracted Power (kW) x Price/kW/month x Occupancy
\`\`\`

Typical pricing:

| Market | Price Range ($/kW/month) |
|--------|-------------------------|
| Johannesburg | $120-150 |
| Lagos | $180-220 |
| Nairobi | $150-180 |
| Cairo | $100-130 |

### Cost Structure

Operating expenses:

- **Power costs** - 40-50% of OpEx
- **Maintenance** - 8-12% of OpEx
- **Staff** - 10-15% of OpEx
- **Insurance** - 2-3% of asset value
- **Property costs** - Varies by location

### Capital Requirements

Typical investment per MW:

| Component | Cost/MW |
|-----------|---------|
| Building & Civil | $3-4M |
| Power Infrastructure | $4-5M |
| Cooling Systems | $2-3M |
| IT Infrastructure | $1-2M |
| Connectivity | $0.5-1M |
| **Total** | **$10-15M** |

## DFI Appetite

### Why DFIs Fund Data Centres

- **Job creation** in high-skill roles
- **Technology transfer** and skills development
- **Economic enablement** for digital services
- **Climate impact** (renewable integration)

### Typical Financing

| Source | Percentage | Terms |
|--------|------------|-------|
| DFI Senior Debt | 50-60% | 10-15 years |
| Commercial Debt | 10-20% | 7-10 years |
| Sponsor Equity | 25-35% | - |

### Key DFI Partners

- **IFC** - Digital infrastructure focus
- **AfDB** - Connect Africa initiative
- **DEG/FMO** - Technology sector appetite
- **US DFC** - Digital economy priority

## Key Metrics

### Operational KPIs

- **Uptime** - 99.99%+ (Tier III/IV)
- **PUE** - Below 1.5 for efficiency
- **Contracted MW** vs installed MW
- **Customer retention** rate

### Financial Metrics

- **EBITDA margins** - 40-55%
- **Revenue per MW** - $1.5-2M annually
- **DSCR** - Above 1.4x
- **Project IRR** - 15-20%

## Risk Factors

### Mitigation Strategies

| Risk | Mitigation |
|------|------------|
| Power reliability | Captive solar + storage |
| Currency | USD-linked contracts |
| Technology obsolescence | Modular, upgradeable design |
| Customer concentration | Diversified tenant base |
| Regulatory | Local partnerships |

---

*Planning a data centre investment? [Contact JASPER](/contact) for digital infrastructure financial modelling.*`,
    category: 'Sector Analysis',
    tags: ['Data Centres', 'Digital Infrastructure', 'Technology', 'Africa', 'DFI', 'Project Finance'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-12-05T10:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-12-05T10:00:00Z',
    readTime: 11,
    featured: false,
    heroImage: null,
    seoTitle: 'Data Centre Financing Africa | Digital Infrastructure Investment',
    seoDescription: 'Finance data centre investments in Africa. Learn site selection, power infrastructure, and DFI funding structures for digital infrastructure projects.',
    seo: { score: 82, title: 'Data Centre Finance Africa', description: 'Digital infrastructure funding' },
    status: 'published',
    createdAt: '2024-12-05T09:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'deepseek-chat'
  },

  // Article 8: IFC Performance Standards
  {
    id: 'post-jasper-008',
    slug: 'ifc-performance-standards-esg-compliance-guide',
    title: 'IFC Performance Standards: ESG Compliance for DFI Funding',
    excerpt: 'Master the IFC Performance Standards that govern DFI investments. Learn how to achieve ESG compliance and navigate environmental and social assessment requirements.',
    content: `## Why IFC Performance Standards Matter

The IFC Performance Standards are the global benchmark for environmental and social (E&S) management in private sector investments. Most DFIs require compliance as a condition of funding.

## The Eight Performance Standards

### PS1: Assessment and Management of E&S Risks

**Requirements:**
- Environmental and Social Impact Assessment (ESIA)
- Environmental and Social Management System (ESMS)
- Stakeholder engagement framework
- Grievance mechanism

**Key Outputs:**
- ESIA report with mitigation measures
- ESMS manual and procedures
- Stakeholder engagement plan
- Monitoring and reporting framework

### PS2: Labour and Working Conditions

**Requirements:**
- Working conditions aligned with national law and ILO standards
- Worker organisations and collective bargaining rights
- Non-discrimination and equal opportunity
- Occupational health and safety

**Key Outputs:**
- HR policies and procedures
- Worker grievance mechanism
- OHS management plan
- Third-party worker standards

### PS3: Resource Efficiency and Pollution Prevention

**Requirements:**
- Resource efficiency measures
- Pollution prevention and control
- Greenhouse gas emissions management
- Hazardous materials handling

**Key Outputs:**
- Resource efficiency audit
- Emissions inventory and reduction plan
- Waste management plan
- Hazmat protocols

### PS4: Community Health, Safety, and Security

**Requirements:**
- Community health and safety assessment
- Security arrangements respecting human rights
- Emergency preparedness and response
- Infrastructure safety

**Key Outputs:**
- Community health and safety plan
- Security management plan
- Emergency response procedures
- Infrastructure safety assessments

### PS5: Land Acquisition and Involuntary Resettlement

**Requirements:**
- Avoidance of involuntary resettlement where feasible
- Compensation at full replacement cost
- Livelihood restoration for affected persons
- Resettlement Action Plan where required

**Key Outputs:**
- Land acquisition due diligence
- Compensation framework
- Livelihood restoration plan
- Resettlement Action Plan (if needed)

### PS6: Biodiversity Conservation

**Requirements:**
- Biodiversity baseline assessment
- Mitigation hierarchy (avoid, minimise, restore, offset)
- Critical habitat protection
- Sustainable management of living natural resources

**Key Outputs:**
- Biodiversity assessment
- Biodiversity Action Plan
- Critical habitat assessment
- Offset strategy (if needed)

### PS7: Indigenous Peoples

**Requirements:**
- Free, Prior, and Informed Consent (FPIC) where required
- Culturally appropriate engagement
- Benefit sharing arrangements
- Impacts on land, resources, and heritage

**Key Outputs:**
- Indigenous Peoples assessment
- FPIC documentation
- Benefit sharing agreement
- Cultural heritage management

### PS8: Cultural Heritage

**Requirements:**
- Chance finds procedures
- Protection of tangible and intangible heritage
- Critical cultural heritage protection
- Project use of cultural heritage

**Key Outputs:**
- Cultural heritage assessment
- Chance finds procedure
- Protection measures
- Community consultation records

## Compliance Process

### Step 1: Categorisation

Projects are categorised by potential impact:

| Category | Impact Level | Requirements |
|----------|--------------|--------------|
| A | High | Full ESIA, all PS applicable |
| B | Moderate | Limited ESIA, relevant PS |
| C | Low | Desktop review |
| FI | Via intermediary | ESMS at FI level |

### Step 2: Assessment

Conduct appropriate studies:

- **Scoping** - Identify key risks and stakeholders
- **Baseline** - Document existing conditions
- **Impact assessment** - Predict project impacts
- **Mitigation** - Design measures to address impacts

### Step 3: Management

Implement ESMS:

- **Policies** - E&S commitment from management
- **Procedures** - Operational controls
- **Monitoring** - KPIs and reporting
- **Continuous improvement** - Audit and update

### Step 4: Disclosure

Share information with:

- **Affected communities** - In appropriate format and language
- **Stakeholders** - Through public disclosure
- **Lenders** - Regular reporting against Action Plan

## Timeline and Costs

### Typical Assessment Timeline

| Activity | Duration | Phase |
|----------|----------|-------|
| Scoping | 1-2 months | Pre-feasibility |
| Baseline studies | 3-6 months | Feasibility |
| ESIA preparation | 3-4 months | Feasibility |
| Disclosure/Consultation | 2-3 months | Pre-financial close |
| ESAP implementation | Ongoing | Construction/Operations |

### Budget Guidance

| Project Size | ESIA Budget | ESMS Setup |
|--------------|-------------|------------|
| Small (<$25M) | $50-100k | $20-50k |
| Medium ($25-100M) | $100-300k | $50-100k |
| Large (>$100M) | $300k-1M | $100-250k |

## Common Pitfalls

1. **Late engagement** - Start E&S early, not at financial close
2. **Underestimating scope** - All eight PS may apply
3. **Consultant quality** - Use IFC-experienced advisors
4. **Stakeholder fatigue** - Genuine, not box-ticking engagement
5. **Budget constraints** - E&S is investment, not cost

---

*Need ESG compliance support? [Contact JASPER](/contact) for E&S advisory and financial modelling integration.*`,
    category: 'DFI Insights',
    tags: ['IFC', 'ESG', 'Performance Standards', 'Environmental', 'Social', 'Compliance', 'DFI'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-12-02T11:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-12-02T11:00:00Z',
    readTime: 14,
    featured: false,
    heroImage: null,
    seoTitle: 'IFC Performance Standards | ESG Compliance Guide for DFI Funding',
    seoDescription: 'Master IFC Performance Standards for DFI funding. Learn ESG compliance requirements, assessment process, and environmental and social management.',
    seo: { score: 87, title: 'IFC Performance Standards', description: 'ESG compliance guide' },
    status: 'published',
    createdAt: '2024-12-02T10:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'gemini-3.0-flash-preview'
  },

  // Article 9: Township Economy Case Study
  {
    id: 'post-jasper-009',
    slug: 'township-economy-investment-case-study-south-africa',
    title: 'Township Economy Investment: A Case Study in Inclusive Finance',
    excerpt: 'How DFIs are financing township-based businesses in South Africa. Learn from real examples of container farms, bakeries, and logistics operations that attracted development finance.',
    content: `## The Township Opportunity

South African townships house over 40% of the population but receive less than 5% of formal investment. DFIs are increasingly targeting this underserved market for its development impact and untapped commercial potential.

## Why DFIs Target Townships

### Development Impact

Township investments deliver:

- **Job creation** in high-unemployment areas
- **Youth employment** for under-35 demographics
- **Women's economic empowerment**
- **Local supply chain development**
- **Skills transfer** and training

### Commercial Rationale

Beyond impact, there's business logic:

- **Underserved markets** with growing consumer demand
- **Lower competition** from formal sector
- **Loyal customer base** in local communities
- **Reduced logistics costs** (produce locally, sell locally)

## Case Study 1: Container Farm

### Project Overview

| Aspect | Detail |
|--------|--------|
| Location | Soweto, Gauteng |
| Product | Hydroponic leafy greens |
| Investment | R21 million |
| Jobs | 35 direct, 100+ indirect |
| Output | 2,000 kg/week |

### Financing Structure

\`\`\`
Total Investment: R21 million
├── IDC Loan: R12.6M (60%) @ Prime - 2%
├── Jobs Fund Grant: R5.2M (25%)
└── Sponsor Equity: R3.2M (15%)
\`\`\`

### Key Success Factors

1. **School offtake agreements** - 40% of production pre-sold
2. **NSNP alignment** - Government school nutrition programme
3. **Youth employment** - 80% of workforce under 30
4. **Technology** - IoT monitoring, solar power

### Financial Performance

| Metric | Year 1 | Year 3 | Year 5 |
|--------|--------|--------|--------|
| Revenue | R5.2M | R12.8M | R18.5M |
| EBITDA | R0.8M | R4.1M | R6.9M |
| DSCR | 0.9x | 1.8x | 2.4x |
| Jobs | 25 | 35 | 45 |

## Case Study 2: Township Bakery

### Project Overview

| Aspect | Detail |
|--------|--------|
| Location | Khayelitsha, Western Cape |
| Product | Bread, rolls, confectionery |
| Investment | R8 million |
| Jobs | 45 direct |
| Output | 15,000 loaves/day |

### Financing Structure

\`\`\`
Total Investment: R8 million
├── SEFA Loan: R4.8M (60%) @ Prime + 1%
├── NEF Grant: R1.6M (20%)
└── Sponsor Equity: R1.6M (20%)
\`\`\`

### Key Success Factors

1. **Spaza shop distribution** - 200+ retail points
2. **BBBEE ownership** - 51% black women-owned
3. **Local sourcing** - 70% inputs from township suppliers
4. **Training programme** - Accredited baking qualifications

## Case Study 3: Last-Mile Logistics

### Project Overview

| Aspect | Detail |
|--------|--------|
| Location | Alexandra, Gauteng |
| Service | E-commerce delivery |
| Investment | R15 million |
| Jobs | 120 direct |
| Fleet | 50 electric bikes, 20 vans |

### Financing Structure

\`\`\`
Total Investment: R15 million
├── IDC Loan: R7.5M (50%) @ Prime
├── DBSA: R4.5M (30%) Concessional
└── Sponsor Equity: R3M (20%)
\`\`\`

### Key Success Factors

1. **E-commerce partnerships** - Takealot, Checkers Sixty60
2. **Electric fleet** - Low operating costs, green credentials
3. **Gig economy model** - Flexible employment
4. **Technology platform** - Real-time tracking, optimization

## Lessons Learned

### What Works

1. **Strong offtake** - Pre-secured customers reduce risk
2. **Local management** - Community trust and knowledge
3. **Appropriate technology** - Fit for context, not over-engineered
4. **Blended finance** - Grants reduce equity burden
5. **Patience** - Longer ramp-up periods acceptable

### Common Challenges

1. **Infrastructure gaps** - Power, water, roads
2. **Security concerns** - Requires community engagement
3. **Skills shortages** - Training investment needed
4. **Informal competition** - Price pressure from spazas
5. **Working capital** - Cash-based economy creates liquidity needs

## DFI Appetite

### Key Funders

| DFI | Focus | Ticket Size |
|-----|-------|-------------|
| IDC | Manufacturing, agri | R5M - R50M |
| SEFA | SMME finance | R50k - R15M |
| NEF | BEE funding | R2M - R75M |
| Jobs Fund | Employment | R5M - R50M (grants) |
| DBSA | Infrastructure | R10M+ |

### Application Tips

1. **Quantify jobs** - IDC measures jobs per R1M invested
2. **Demonstrate BEE** - Black ownership and management
3. **Show community buy-in** - Letters of support, partnerships
4. **Realistic projections** - Conservative assumptions win
5. **Strong sponsors** - Track record in township business

---

*Planning a township investment? [Contact JASPER](/contact) for inclusive finance modelling.*`,
    category: 'Case Studies',
    tags: ['Township Economy', 'South Africa', 'IDC', 'Inclusive Finance', 'Case Study', 'DFI', 'SME'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-11-28T09:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-11-28T09:00:00Z',
    readTime: 12,
    featured: false,
    heroImage: null,
    seoTitle: 'Township Economy Investment | Inclusive Finance Case Study South Africa',
    seoDescription: 'Learn how DFIs finance township businesses in South Africa. Real case studies of container farms, bakeries, and logistics operations attracting development finance.',
    seo: { score: 83, title: 'Township Investment Case Study', description: 'Inclusive finance examples' },
    status: 'published',
    createdAt: '2024-11-28T08:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'deepseek-chat'
  },

  // Article 10: 2025 DFI Outlook
  {
    id: 'post-jasper-010',
    slug: 'dfi-funding-outlook-2025-africa-development-finance',
    title: 'DFI Funding Outlook 2025: What African Project Developers Need to Know',
    excerpt: 'What are the key trends shaping DFI funding in 2025? From climate finance surge to digitalisation priorities, discover where development finance institutions are directing capital.',
    content: `## The State of DFI Funding

Development Finance Institutions deployed over $200 billion globally in 2024, with Africa receiving approximately 15% of flows. For 2025, several trends will shape where this capital goes.

## Key Trends for 2025

### 1. Climate Finance Dominance

Climate-linked investments will dominate DFI portfolios:

- **Net-zero commitments** driving portfolio greening
- **Just transition** financing for coal-dependent regions
- **Adaptation focus** increasing in vulnerable countries
- **Nature-based solutions** gaining traction

**Implication:** Projects with strong climate rationale will be prioritised. Carbon accounting and climate impact quantification are essential.

### 2. Blended Finance Expansion

DFIs are increasingly using blended structures:

- **Concessional tranches** to de-risk commercial capital
- **First-loss guarantees** attracting institutional investors
- **Technical assistance** grants for project preparation
- **Results-based financing** tied to outcomes

**Implication:** Expect multi-party financing with complex structures. Financial models must accommodate diverse funding sources.

### 3. Digitalisation as Enabler

Digital infrastructure is priority across DFIs:

- **Connectivity** - Data centres, fibre, satellite
- **Fintech** - Payment systems, digital banking
- **AgriTech** - Precision farming, market platforms
- **GovTech** - E-government, digital ID systems

**Implication:** Projects incorporating digital elements gain preference. Technology components strengthen applications.

### 4. Gender Lens Investing

Gender-focused investments are expanding:

- **2X Challenge** - G7 commitment to women's economic empowerment
- **Gender bonds** - Dedicated financing instruments
- **Supply chain inclusion** - Women-owned supplier development
- **Leadership requirements** - Board and management diversity

**Implication:** Demonstrate women's participation throughout value chain. Gender action plans are increasingly mandatory.

### 5. Local Currency Solutions

DFIs are addressing currency mismatch:

- **Local currency lending** expansion
- **TCX hedging facility** growth
- **Domestic capital market** development
- **Partial credit guarantees** for local banks

**Implication:** Local currency financing is more accessible. Factor into financial structuring for better terms.

## Sector Priorities by DFI

### IFC (World Bank Group)

| Priority Sector | 2025 Target |
|-----------------|-------------|
| Climate | 35% of portfolio |
| Infrastructure | $15B annually |
| Financial institutions | $10B annually |
| Manufacturing | Growing focus |

### AfDB

| Priority Sector | Initiative |
|-----------------|------------|
| Energy | Desert to Power |
| Agriculture | Feed Africa |
| Industrialisation | Industrialise Africa |
| Integration | Integrate Africa |

### DEG (Germany)

- **Green transition** - Renewable energy, sustainable industry
- **Employment** - Job-intensive investments
- **Financial sector** - Banking and insurance
- **Healthcare** - Post-COVID priorities

### FMO (Netherlands)

- **Energy** - Sustainable generation and access
- **Agribusiness** - Inclusive value chains
- **Financial institutions** - MSME lending
- **Infrastructure** - Ports, logistics, housing

## Regional Outlook

### North Africa

- **Morocco** - Renewables hub, automotive manufacturing
- **Egypt** - Infrastructure mega-projects, green hydrogen
- **Tunisia** - ICT services, agri-processing

### West Africa

- **Nigeria** - Energy transition, digital economy
- **Ghana** - Mining, agri-processing
- **Senegal** - Gas development, infrastructure

### East Africa

- **Kenya** - Green financing pioneer, digital leadership
- **Ethiopia** - Manufacturing, agribusiness (post-reform)
- **Tanzania** - Mining, agriculture

### Southern Africa

- **South Africa** - Just transition, renewable energy
- **Zambia** - Mining, agriculture
- **Mozambique** - LNG (cautious), renewables

## Preparing for 2025

### Strategic Positioning

1. **Climate alignment** - Ensure project contributes to NDC/net-zero
2. **Impact metrics** - Quantify development outcomes early
3. **ESG excellence** - Exceed minimum standards
4. **Gender integration** - Embed women's empowerment throughout
5. **Local partnerships** - Demonstrate domestic value creation

### Financial Model Updates

Incorporate these elements:

- **Carbon accounting** - Emissions avoided/reduced
- **Gender metrics** - Jobs by gender, ownership, supply chain
- **SDG mapping** - Contribution to relevant goals
- **Additionality** - What DFI capital enables
- **Concessionality justification** - Why subsidised terms needed

### Application Enhancement

Strengthen proposals with:

- **Climate vulnerability assessment** for adaptation projects
- **Just transition narrative** for carbon-intensive regions
- **Digital integration** wherever relevant
- **Local currency structuring** where available
- **Blended finance readiness** for multi-party deals

## Conclusion

2025 presents significant opportunities for well-prepared project developers. Climate focus, gender lens, and digital enablement are no longer optional add-ons but core requirements for DFI funding.

---

*Ready to position your project for 2025 DFI funding? [Contact JASPER](/contact) for strategic advisory and financial modelling.*`,
    category: 'Industry News',
    tags: ['DFI', '2025 Outlook', 'Africa', 'Climate Finance', 'Development Finance', 'Investment Trends'],
    author: {
      name: 'JASPER AI',
      role: 'Content Generation System'
    },
    publishedAt: '2024-11-25T10:00:00Z',
    scheduledAt: null,
    updatedAt: '2024-11-25T10:00:00Z',
    readTime: 13,
    featured: false,
    heroImage: null,
    seoTitle: 'DFI Funding Outlook 2025 | Africa Development Finance Trends',
    seoDescription: 'Discover DFI funding trends for 2025 in Africa. From climate finance to digitalisation priorities, learn where development finance institutions are directing capital.',
    seo: { score: 89, title: 'DFI Outlook 2025', description: 'Development finance trends' },
    status: 'published',
    createdAt: '2024-11-25T09:00:00Z',
    createdBy: 'ai-system',
    viewCount: 0,
    aiGenerated: true,
    generationModel: 'gemini-3.0-flash-preview'
  }
];

// ============================================================================
// API Functions
// ============================================================================

function generateId() {
  return `post-${Date.now().toString(36)}-${Math.random().toString(36).substr(2, 6)}`;
}

function generateSlug(title) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

function calculateReadTime(content) {
  const wordCount = content.split(/\s+/).length;
  return Math.ceil(wordCount / 200);
}

function getPublishedPosts() {
  const now = new Date();
  return blogPosts.filter(post => {
    if (post.status !== 'published') return false;
    if (post.scheduledAt && new Date(post.scheduledAt) > now) return false;
    return true;
  });
}

function processScheduledPosts() {
  const now = new Date();
  let publishedCount = 0;

  blogPosts.forEach(post => {
    if (post.status === 'scheduled' && post.scheduledAt) {
      if (new Date(post.scheduledAt) <= now) {
        post.status = 'published';
        post.publishedAt = now.toISOString();
        post.updatedAt = now.toISOString();
        publishedCount++;
      }
    }
  });

  return publishedCount;
}

export default async function handler(req, res) {
  // CORS
  const allowedOrigins = [
    'https://jasperfinance.org',
    'https://portal.jasperfinance.org',
    'http://localhost:3000',
    'http://localhost:3004'
  ];
  const origin = req.headers.origin;
  if (allowedOrigins.includes(origin)) {
    res.setHeader('Access-Control-Allow-Origin', origin);
  }
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-AI-API-Key');
  res.setHeader('Access-Control-Allow-Credentials', 'true');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // GET - Public access for published posts, admin access for all
  if (req.method === 'GET') {
    const { id, slug, category, tag, search, status, featured, page = 1, limit = 50, admin } = req.query;

    // Admin mode requires authentication
    if (admin === 'true') {
      const user = await verifyAuth(req);
      if (!user) {
        return res.status(401).json({ success: false, message: 'Authentication required for admin access' });
      }

      if (id) {
        const post = blogPosts.find(p => p.id === id);
        if (!post) {
          return res.status(404).json({ success: false, message: 'Post not found' });
        }
        return res.status(200).json({ success: true, post });
      }

      let filteredPosts = [...blogPosts];

      if (status) {
        filteredPosts = filteredPosts.filter(p => p.status === status);
      }

      filteredPosts.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

      const startIndex = (page - 1) * limit;
      const paginatedPosts = filteredPosts.slice(startIndex, startIndex + parseInt(limit));

      const stats = {
        total: blogPosts.length,
        published: blogPosts.filter(p => p.status === 'published').length,
        scheduled: blogPosts.filter(p => p.status === 'scheduled').length,
        draft: blogPosts.filter(p => p.status === 'draft').length
      };

      return res.status(200).json({
        success: true,
        posts: paginatedPosts,
        pagination: {
          page: parseInt(page),
          limit: parseInt(limit),
          total: filteredPosts.length,
          totalPages: Math.ceil(filteredPosts.length / limit)
        },
        stats
      });
    }

    // Public access - only published posts
    let posts = getPublishedPosts();

    if (slug) {
      const post = posts.find(p => p.slug === slug);
      if (!post) {
        return res.status(404).json({ success: false, message: 'Post not found' });
      }
      const originalPost = blogPosts.find(p => p.slug === slug);
      if (originalPost) {
        originalPost.viewCount = (originalPost.viewCount || 0) + 1;
      }
      return res.status(200).json({ success: true, post });
    }

    if (category) {
      posts = posts.filter(p => p.category === category);
    }

    if (tag) {
      posts = posts.filter(p => p.tags.includes(tag));
    }

    if (search) {
      const searchLower = search.toLowerCase();
      posts = posts.filter(p =>
        p.title.toLowerCase().includes(searchLower) ||
        p.excerpt.toLowerCase().includes(searchLower) ||
        p.content.toLowerCase().includes(searchLower)
      );
    }

    if (featured === 'true') {
      posts = posts.filter(p => p.featured);
    }

    posts.sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());

    const startIndex = (page - 1) * limit;
    const paginatedPosts = posts.slice(startIndex, startIndex + parseInt(limit));

    const featuredPost = posts.find(p => p.featured);

    const categories = CATEGORIES.map(cat => ({
      name: cat,
      count: posts.filter(p => p.category === cat).length
    }));

    return res.status(200).json({
      success: true,
      posts: paginatedPosts,
      featuredPost,
      categories,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total: posts.length,
        totalPages: Math.ceil(posts.length / limit)
      }
    });
  }

  // POST - Create new post (admin or AI)
  if (req.method === 'POST') {
    const user = await verifyAuth(req);
    const isAI = verifyAIKey(req);

    if (!user && !isAI) {
      return res.status(401).json({ success: false, message: 'Authentication required' });
    }

    try {
      const {
        title,
        excerpt,
        content,
        category,
        tags = [],
        author,
        scheduledAt,
        featured = false,
        heroImage,
        seoTitle,
        seoDescription,
        status = 'draft'
      } = req.body;

      if (!title || !content || !category) {
        return res.status(400).json({
          success: false,
          message: 'Title, content, and category are required'
        });
      }

      if (!CATEGORIES.includes(category)) {
        return res.status(400).json({
          success: false,
          message: `Invalid category. Must be one of: ${CATEGORIES.join(', ')}`
        });
      }

      if (!POST_STATUSES.includes(status)) {
        return res.status(400).json({
          success: false,
          message: `Invalid status. Must be one of: ${POST_STATUSES.join(', ')}`
        });
      }

      let slug = generateSlug(title);
      let slugCounter = 1;
      let originalSlug = slug;
      while (blogPosts.some(p => p.slug === slug)) {
        slug = `${originalSlug}-${slugCounter}`;
        slugCounter++;
      }

      const now = new Date().toISOString();
      const newPost = {
        id: generateId(),
        slug,
        title,
        excerpt: excerpt || content.substring(0, 200).replace(/[#*`]/g, '') + '...',
        content,
        category,
        tags: Array.isArray(tags) ? tags : [],
        author: author || {
          name: isAI ? 'JASPER AI' : (user?.name || 'JASPER Team'),
          role: isAI ? 'Content Generation System' : 'Financial Architecture'
        },
        publishedAt: status === 'published' ? now : null,
        scheduledAt: status === 'scheduled' ? scheduledAt : null,
        updatedAt: now,
        readTime: calculateReadTime(content),
        featured,
        heroImage: heroImage || null,
        seoTitle: seoTitle || title,
        seoDescription: seoDescription || excerpt || content.substring(0, 160),
        seo: { score: 75, title: seoTitle || title, description: seoDescription },
        status,
        createdAt: now,
        createdBy: isAI ? 'ai-system' : (user?.email || 'admin'),
        viewCount: 0,
        aiGenerated: isAI
      };

      blogPosts.unshift(newPost);

      return res.status(201).json({
        success: true,
        post: newPost,
        message: status === 'scheduled'
          ? `Post scheduled for ${new Date(scheduledAt).toLocaleString()}`
          : status === 'published'
          ? 'Post published successfully'
          : 'Draft saved successfully'
      });
    } catch (error) {
      console.error('Create post error:', error);
      return res.status(500).json({
        success: false,
        message: 'Failed to create post'
      });
    }
  }

  // PUT/PATCH - Update post (admin only)
  if (req.method === 'PUT' || req.method === 'PATCH') {
    const user = await verifyAuth(req);
    if (!user) {
      return res.status(401).json({ success: false, message: 'Authentication required' });
    }

    try {
      const { id } = req.query;
      const updates = req.body;

      if (!id) {
        return res.status(400).json({ success: false, message: 'Post ID is required' });
      }

      const postIndex = blogPosts.findIndex(p => p.id === id);
      if (postIndex === -1) {
        return res.status(404).json({ success: false, message: 'Post not found' });
      }

      if (updates.status && !POST_STATUSES.includes(updates.status)) {
        return res.status(400).json({
          success: false,
          message: `Invalid status. Must be one of: ${POST_STATUSES.join(', ')}`
        });
      }

      if (updates.category && !CATEGORIES.includes(updates.category)) {
        return res.status(400).json({
          success: false,
          message: `Invalid category. Must be one of: ${CATEGORIES.join(', ')}`
        });
      }

      if (updates.title && updates.title !== blogPosts[postIndex].title) {
        let newSlug = generateSlug(updates.title);
        let slugCounter = 1;
        let originalSlug = newSlug;
        while (blogPosts.some((p, i) => i !== postIndex && p.slug === newSlug)) {
          newSlug = `${originalSlug}-${slugCounter}`;
          slugCounter++;
        }
        updates.slug = newSlug;
      }

      if (updates.content) {
        updates.readTime = calculateReadTime(updates.content);
      }

      if (updates.status === 'published' && blogPosts[postIndex].status !== 'published') {
        updates.publishedAt = new Date().toISOString();
      }

      blogPosts[postIndex] = {
        ...blogPosts[postIndex],
        ...updates,
        updatedAt: new Date().toISOString()
      };

      return res.status(200).json({
        success: true,
        post: blogPosts[postIndex]
      });
    } catch (error) {
      console.error('Update post error:', error);
      return res.status(500).json({
        success: false,
        message: 'Failed to update post'
      });
    }
  }

  // DELETE - Delete post (admin only)
  if (req.method === 'DELETE') {
    const user = await verifyAuth(req);
    if (!user) {
      return res.status(401).json({ success: false, message: 'Authentication required' });
    }

    try {
      const { id } = req.query;

      if (!id) {
        return res.status(400).json({ success: false, message: 'Post ID is required' });
      }

      const postIndex = blogPosts.findIndex(p => p.id === id);
      if (postIndex === -1) {
        return res.status(404).json({ success: false, message: 'Post not found' });
      }

      const deletedPost = blogPosts.splice(postIndex, 1)[0];

      return res.status(200).json({
        success: true,
        message: 'Post deleted',
        post: deletedPost
      });
    } catch (error) {
      console.error('Delete post error:', error);
      return res.status(500).json({
        success: false,
        message: 'Failed to delete post'
      });
    }
  }

  return res.status(405).json({
    success: false,
    message: 'Method not allowed'
  });
}

export { blogPosts, getPublishedPosts, processScheduledPosts, CATEGORIES };
