"""Initial schema - all tables

Revision ID: 00bcfcbbe4d2
Revises: 
Create Date: 2025-12-10 04:38:34.094345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bcfcbbe4d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trading_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.Enum('RENEWABLE_ENERGY', 'INFRASTRUCTURE', 'AGRICULTURE', 'MANUFACTURING', 'HEALTHCARE', 'EDUCATION', 'TECHNOLOGY', 'REAL_ESTATE', 'MINING', 'WATER_SANITATION', 'TRANSPORT', 'TELECOM', 'OTHER', name='industry'), nullable=False),
    sa.Column('status', sa.Enum('LEAD', 'PROSPECT', 'CLIENT', 'INACTIVE', 'CHURNED', name='companystatus'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dfi_targets', sa.JSON(), nullable=True, comment="List of target DFIs: ['ifc', 'afdb']"),
    sa.Column('project_value_min', sa.Integer(), nullable=True, comment='Minimum project value in USD'),
    sa.Column('project_value_max', sa.Integer(), nullable=True, comment='Maximum project value in USD'),
    sa.Column('lead_source', sa.String(length=100), nullable=True, comment='How they found us: website, referral, linkedin, conference'),
    sa.Column('referred_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Primary contact for the company'),
    sa.Column('is_decision_maker', sa.Boolean(), nullable=False, comment='Can authorise payments/contracts'),
    sa.Column('portal_access', sa.Boolean(), nullable=False, comment='Can access client portal'),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('accepts_marketing', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('magic_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP that requested the link'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='Browser user agent'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_links_contact_id'), 'magic_links', ['contact_id'], unique=False)
    op.create_index(op.f('ix_magic_links_id'), 'magic_links', ['id'], unique=False)
    op.create_index(op.f('ix_magic_links_token'), 'magic_links', ['token'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True, comment='Primary contact for this project'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Project name (e.g., 'Solar Farm Feasibility Study')"),
    sa.Column('reference', sa.String(length=50), nullable=False, comment="Project reference (e.g., 'JASP-2025-001')"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.Enum('INQUIRY', 'QUALIFY', 'INTAKE', 'PROPOSAL', 'DEPOSIT', 'PRODUCTION', 'DRAFT', 'FINAL', name='projectstage'), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(), nullable=False, comment='When stage last changed'),
    sa.Column('package', sa.Enum('GROWTH', 'INSTITUTIONAL', 'INFRASTRUCTURE', 'CUSTOM', name='package'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False, comment='Project value in primary currency'),
    sa.Column('currency', sa.Enum('USD', 'ZAR', 'EUR', 'GBP', name='currency'), nullable=False),
    sa.Column('inquiry_date', sa.Date(), nullable=False, comment='When inquiry received'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='When production started'),
    sa.Column('target_completion', sa.Date(), nullable=True, comment='Target delivery date'),
    sa.Column('actual_completion', sa.Date(), nullable=True, comment='Actual delivery date'),
    sa.Column('revision_rounds_used', sa.Integer(), nullable=False, comment='Number of revision rounds used'),
    sa.Column('revision_rounds_total', sa.Integer(), nullable=False, comment='Total revision rounds included'),
    sa.Column('project_sector', sa.String(length=100), nullable=True),
    sa.Column('project_location', sa.String(length=255), nullable=True),
    sa.Column('funding_amount', sa.Integer(), nullable=True, comment='Target funding amount in USD'),
    sa.Column('target_dfis', sa.JSON(), nullable=True, comment="Target DFIs: ['ifc', 'afdb']"),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True, comment='Internal notes not visible to client'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_projects_contact_id'), 'projects', ['contact_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_reference'), 'projects', ['reference'], unique=True)
    op.create_index(op.f('ix_projects_stage'), 'projects', ['stage'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original uploaded filename'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Storage path'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME type'),
    sa.Column('file_extension', sa.String(length=20), nullable=False, comment='File extension without dot'),
    sa.Column('document_type', sa.Enum('FEASIBILITY_STUDY', 'FINANCIAL_STATEMENTS', 'REGISTRATION_DOCS', 'TECHNICAL_SPECS', 'ENVIRONMENTAL_STUDY', 'PERMITS_LICENSES', 'CONTRACTS', 'OTHER_CLIENT', 'PROPOSAL', 'FINANCIAL_MODEL', 'BUSINESS_PLAN', 'PITCH_DECK', 'EXECUTIVE_SUMMARY', 'DUE_DILIGENCE', 'INVOICE', 'OTHER_DELIVERABLE', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'PROCESSING', 'PROCESSED', 'APPROVED', 'REJECTED', 'ARCHIVED', name='documentstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number'),
    sa.Column('is_latest', sa.Boolean(), nullable=False, comment='Is this the latest version'),
    sa.Column('replaces_id', sa.Integer(), nullable=True, comment='ID of document this replaces'),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False, comment="Who uploaded: 'client' or admin email"),
    sa.Column('is_client_upload', sa.Boolean(), nullable=False, comment='Uploaded by client vs JASPER'),
    sa.Column('ocr_processed', sa.Boolean(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True, comment='JSON from AI extraction'),
    sa.Column('client_visible', sa.Boolean(), nullable=False, comment='Visible in client portal'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False, comment='Needs admin approval before visible'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.Enum('EMAIL_SENT', 'EMAIL_RECEIVED', 'CALL', 'MEETING', 'VIDEO_CALL', 'NOTE', 'INTERNAL_NOTE', 'STAGE_CHANGE', 'DOCUMENT_UPLOADED', 'DOCUMENT_DOWNLOADED', 'INVOICE_SENT', 'INVOICE_PAID', 'PROPOSAL_SENT', 'PROPOSAL_VIEWED', 'PORTAL_LOGIN', 'FORM_SUBMITTED', 'TASK_CREATED', 'TASK_COMPLETED', 'REMINDER', name='interactiontype'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False, comment='Brief description of the interaction'),
    sa.Column('content', sa.Text(), nullable=True, comment='Full content/notes'),
    sa.Column('email_message_id', sa.String(length=255), nullable=True, comment='Email Message-ID header for threading'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Duration for calls/meetings'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='Scheduled time for meetings'),
    sa.Column('outcome', sa.String(length=500), nullable=True, comment='Outcome/result of call/meeting'),
    sa.Column('from_stage', sa.String(length=50), nullable=True),
    sa.Column('to_stage', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment="Who created: email or 'system'"),
    sa.Column('is_system_generated', sa.Boolean(), nullable=False, comment='Auto-generated vs manual'),
    sa.Column('internal_only', sa.Boolean(), nullable=False, comment='Hidden from client portal'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_company_id'), 'interactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_interactions_contact_id'), 'interactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_interactions_created_at'), 'interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_index(op.f('ix_interactions_interaction_type'), 'interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_interactions_project_id'), 'interactions', ['project_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False, comment='Format: INV-2025-001'),
    sa.Column('invoice_type', sa.Enum('DEPOSIT', 'FINAL', 'FULL', 'CUSTOM', name='invoicetype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Invoice amount in cents (or smallest unit)'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('crypto_discount_applied', sa.Boolean(), nullable=False, comment='3% crypto discount applied'),
    sa.Column('discount_amount', sa.Integer(), nullable=False, comment='Discount amount in cents'),
    sa.Column('final_amount', sa.Integer(), nullable=False, comment='Final amount after discounts'),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.Enum('BANK_TRANSFER', 'PAYPAL', 'USDT_TRC20', 'USDC_ERC20', 'BTC', 'OTHER', name='paymentmethod'), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True, comment='Transaction ID or reference'),
    sa.Column('payment_notes', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True, comment='Path to generated PDF'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_project_id'), 'invoices', ['project_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False, comment='Order in milestone sequence'),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_project_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_interactions_project_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_interaction_type'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_created_at'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_contact_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_company_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_projects_stage'), table_name='projects')
    op.drop_index(op.f('ix_projects_reference'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_contact_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_magic_links_token'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_id'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_contact_id'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
